import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-hotel-group-corporate-rate-leakage-recovery",
  "engine": "recovery",
  "title": "Hotel Group & Corporate Rate Leakage Recovery",
  "shortTitle": "Hotel Group and Corporate Rate Leakage Recovery",
  "tagline": "Find hotel revenue leakage from incorrect negotiated rates, concessions, room blocks, commissions, and rate-code misuse.",
  "industry": "Hospitality Revenue Assurance",
  "buyer": "Hotel groups and management companies",
  "uiPort": 4735,
  "apiPort": 5735,
  "accent": "#be123c",
  "currency": "USD",
  "primaryOutcome": "Hotel Group & Corporate Rate Leakage Recovery converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect negotiated rate agreements, room inventory, reservations, stay dates, rate codes, blackout dates, last-room availability, commissions, folios, and payments in one accountable workflow. Find hotel revenue leakage from incorrect negotiated rates, concessions, room blocks, commissions, and rate-code misuse.",
  "calculation": {
    "actualKey": "receivedAmount",
    "expectedKey": "entitledAmount",
    "actualLabel": "Received or Recognized Amount",
    "expectedLabel": "Contract or Rule-Supported Entitlement",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Hotel Group & Corporate Rate Leakage Recovery evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("rate-agreement-library","HGC01","Rate agreement library","Execute rate agreement library using negotiated rate agreements, room inventory, reservations, stay dates, rate codes, blackout dates, last-room availability, commissions, folios, and payments.","Produce a governed rate agreement library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Hotel / Negotiated Account","text","Hotel / Negotiated Account · Standard Case"],["caseReference","Rate agreement library Reference","text","HGC01-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1772500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2144725],["domainDriver","Rate Program","select","Corporate negotiated",["Corporate negotiated","Group block","Government rate"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Rate agreement library case","Account property mapping case","Room block registry case","Reservation ingestion case","Rate code validation case"]}),
feature("account-property-mapping","HGC02","Account property mapping","Execute account property mapping using negotiated rate agreements, room inventory, reservations, stay dates, rate codes, blackout dates, last-room availability, commissions, folios, and payments.","Produce a governed account property mapping decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Hotel / Negotiated Account","text","Hotel / Negotiated Account · Standard Case"],["caseReference","Account property mapping Reference","text","HGC02-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1772500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2144725],["domainDriver","Rate Program","select","Corporate negotiated",["Corporate negotiated","Group block","Government rate"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Rate agreement library case","Account property mapping case","Room block registry case","Reservation ingestion case","Rate code validation case"]}),
feature("room-block-registry","HGC03","Room block registry","Execute room block registry using negotiated rate agreements, room inventory, reservations, stay dates, rate codes, blackout dates, last-room availability, commissions, folios, and payments.","Produce a governed room block registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Hotel / Negotiated Account","text","Hotel / Negotiated Account · Standard Case"],["caseReference","Room block registry Reference","text","HGC03-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1772500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2144725],["domainDriver","Rate Program","select","Corporate negotiated",["Corporate negotiated","Group block","Government rate"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Rate agreement library case","Account property mapping case","Room block registry case","Reservation ingestion case","Rate code validation case"]}),
feature("reservation-ingestion","HGC04","Reservation ingestion","Execute reservation ingestion using negotiated rate agreements, room inventory, reservations, stay dates, rate codes, blackout dates, last-room availability, commissions, folios, and payments.","Produce a governed reservation ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Hotel / Negotiated Account","text","Hotel / Negotiated Account · Standard Case"],["caseReference","Reservation ingestion Reference","text","HGC04-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1772500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2144725],["domainDriver","Rate Program","select","Corporate negotiated",["Corporate negotiated","Group block","Government rate"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Rate agreement library case","Account property mapping case","Room block registry case","Reservation ingestion case","Rate code validation case"]}),
feature("rate-code-validation","HGC05","Rate code validation","Execute rate code validation using negotiated rate agreements, room inventory, reservations, stay dates, rate codes, blackout dates, last-room availability, commissions, folios, and payments.","Produce a governed rate code validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Hotel / Negotiated Account","text","Hotel / Negotiated Account · Standard Case"],["caseReference","Rate code validation Reference","text","HGC05-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1772500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2144725],["domainDriver","Rate Program","select","Corporate negotiated",["Corporate negotiated","Group block","Government rate"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Rate agreement library case","Account property mapping case","Room block registry case","Reservation ingestion case","Rate code validation case"]}),
feature("stay-date-eligibility","HGC06","Stay-date eligibility","Execute stay-date eligibility using negotiated rate agreements, room inventory, reservations, stay dates, rate codes, blackout dates, last-room availability, commissions, folios, and payments.","Produce a governed stay-date eligibility decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Hotel / Negotiated Account","text","Hotel / Negotiated Account · Standard Case"],["caseReference","Stay-date eligibility Reference","text","HGC06-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1772500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2144725],["domainDriver","Rate Program","select","Corporate negotiated",["Corporate negotiated","Group block","Government rate"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Rate agreement library case","Account property mapping case","Room block registry case","Reservation ingestion case","Rate code validation case"]}),
feature("blackout-date-control","HGC07","Blackout date control","Execute blackout date control using negotiated rate agreements, room inventory, reservations, stay dates, rate codes, blackout dates, last-room availability, commissions, folios, and payments.","Produce a governed blackout date control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Hotel / Negotiated Account","text","Hotel / Negotiated Account · Standard Case"],["caseReference","Blackout date control Reference","text","HGC07-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1772500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2144725],["domainDriver","Rate Program","select","Corporate negotiated",["Corporate negotiated","Group block","Government rate"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Rate agreement library case","Account property mapping case","Room block registry case","Reservation ingestion case","Rate code validation case"]}),
feature("last-room-availability","HGC08","Last-room availability","Execute last-room availability using negotiated rate agreements, room inventory, reservations, stay dates, rate codes, blackout dates, last-room availability, commissions, folios, and payments.","Produce a governed last-room availability decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Hotel / Negotiated Account","text","Hotel / Negotiated Account · Standard Case"],["caseReference","Last-room availability Reference","text","HGC08-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1772500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2144725],["domainDriver","Rate Program","select","Corporate negotiated",["Corporate negotiated","Group block","Government rate"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Rate agreement library case","Account property mapping case","Room block registry case","Reservation ingestion case","Rate code validation case"]}),
feature("concession-package-audit","HGC09","Concession package audit","Execute concession package audit using negotiated rate agreements, room inventory, reservations, stay dates, rate codes, blackout dates, last-room availability, commissions, folios, and payments.","Produce a governed concession package audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Hotel / Negotiated Account","text","Hotel / Negotiated Account · Standard Case"],["caseReference","Concession package audit Reference","text","HGC09-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1772500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2144725],["domainDriver","Rate Program","select","Corporate negotiated",["Corporate negotiated","Group block","Government rate"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Rate agreement library case","Account property mapping case","Room block registry case","Reservation ingestion case","Rate code validation case"]}),
feature("attrition-calculation","HGC10","Attrition calculation","Execute attrition calculation using negotiated rate agreements, room inventory, reservations, stay dates, rate codes, blackout dates, last-room availability, commissions, folios, and payments.","Produce a governed attrition calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Hotel / Negotiated Account","text","Hotel / Negotiated Account · Standard Case"],["caseReference","Attrition calculation Reference","text","HGC10-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1772500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2144725],["domainDriver","Rate Program","select","Corporate negotiated",["Corporate negotiated","Group block","Government rate"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Rate agreement library case","Account property mapping case","Room block registry case","Reservation ingestion case","Rate code validation case"]}),
feature("cancellation-fee-validation","HGC11","Cancellation fee validation","Execute cancellation fee validation using negotiated rate agreements, room inventory, reservations, stay dates, rate codes, blackout dates, last-room availability, commissions, folios, and payments.","Produce a governed cancellation fee validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Hotel / Negotiated Account","text","Hotel / Negotiated Account · Standard Case"],["caseReference","Cancellation fee validation Reference","text","HGC11-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1772500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2144725],["domainDriver","Rate Program","select","Corporate negotiated",["Corporate negotiated","Group block","Government rate"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Rate agreement library case","Account property mapping case","Room block registry case","Reservation ingestion case","Rate code validation case"]}),
feature("commission-treatment","HGC12","Commission treatment","Execute commission treatment using negotiated rate agreements, room inventory, reservations, stay dates, rate codes, blackout dates, last-room availability, commissions, folios, and payments.","Produce a governed commission treatment decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Hotel / Negotiated Account","text","Hotel / Negotiated Account · Standard Case"],["caseReference","Commission treatment Reference","text","HGC12-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1772500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2144725],["domainDriver","Rate Program","select","Corporate negotiated",["Corporate negotiated","Group block","Government rate"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Rate agreement library case","Account property mapping case","Room block registry case","Reservation ingestion case","Rate code validation case"]}),
feature("folio-rate-correction","HGC13","Folio rate correction","Execute folio rate correction using negotiated rate agreements, room inventory, reservations, stay dates, rate codes, blackout dates, last-room availability, commissions, folios, and payments.","Produce a governed folio rate correction decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Hotel / Negotiated Account","text","Hotel / Negotiated Account · Standard Case"],["caseReference","Folio rate correction Reference","text","HGC13-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1772500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2144725],["domainDriver","Rate Program","select","Corporate negotiated",["Corporate negotiated","Group block","Government rate"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Rate agreement library case","Account property mapping case","Room block registry case","Reservation ingestion case","Rate code validation case"]}),
feature("account-recovery-workflow","HGC14","Account recovery workflow","Execute account recovery workflow using negotiated rate agreements, room inventory, reservations, stay dates, rate codes, blackout dates, last-room availability, commissions, folios, and payments.","Produce a governed account recovery workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Hotel / Negotiated Account","text","Hotel / Negotiated Account · Standard Case"],["caseReference","Account recovery workflow Reference","text","HGC14-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1772500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2144725],["domainDriver","Rate Program","select","Corporate negotiated",["Corporate negotiated","Group block","Government rate"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Rate agreement library case","Account property mapping case","Room block registry case","Reservation ingestion case","Rate code validation case"]}),
feature("property-account-analytics","HGC15","Property account analytics","Execute property account analytics using negotiated rate agreements, room inventory, reservations, stay dates, rate codes, blackout dates, last-room availability, commissions, folios, and payments.","Produce a governed property account analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Hotel / Negotiated Account","text","Hotel / Negotiated Account · Standard Case"],["caseReference","Property account analytics Reference","text","HGC15-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1772500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2144725],["domainDriver","Rate Program","select","Corporate negotiated",["Corporate negotiated","Group block","Government rate"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Rate agreement library case","Account property mapping case","Room block registry case","Reservation ingestion case","Rate code validation case"]})
]);
